#!/bin/bash

printf '*%.0s' {1..78}
echo
echo "Cleaning up git history ..."
printf '*%.0s' {1..78}
echo
git ls-files > keep-these.txt
echo "Keeping:"
cat keep-these.txt

git filter-branch --force --index-filter \
  "git rm  --ignore-unmatch --cached -qr . ; \
  cat $PWD/keep-these.txt | xargs git reset -q \$GIT_COMMIT --" \
  --prune-empty --tag-name-filter cat -- --all


rm -rf .git/refs/original/
git reflog expire --expire=now --all
git gc --aggressive --prune=now
rm keep-these.txt
